#spring.application.name=gestionProjet
#spring.datasource.url=jdbc:mysql://localhost:3306/gestionProjet
#spring.datasource.username=root
#spring.datasource.password=Di@lloODC5
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#server.port=8081
#
#springdoc.swagger-ui.use-root-path=true
#
#
##configuration de emailSender
#spring.mail.default-encoding=UTF-8
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=salioufereya19@gmail.com
#spring.mail.password=edellpbqcsexllks
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#
#
#spring.servlet.multipart.max-file-size=10MB
#spring.servlet.multipart.max-request-size=10MB
#
#
#cloud.aws.s3.bucket=nom-du-bucket
#cloud.aws.credentials.access-key=YOUR_ACCESS_KEY
#cloud.aws.credentials.secret-key=YOUR_SECRET_KEY
#cloud.aws.region.static=us-west-2
#
#
#
#
#
#logging.level.root=DEBUG
#logging.level.org.springframework=DEBUG
#logging.level.org.springframework.orm.jpa=DEBUG
#logging.level.com.itma.gestionProjet=TRACE
#

spring.application.name=gestionProjet
spring.datasource.url=jdbc:mysql://localhost:3306/gestionProjet
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
server.port=8081

springdoc.swagger-ui.use-root-path=true


#configuration de emailSender
spring.mail.default-encoding=UTF-8
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=salioufereya19@gmail.com
spring.mail.password=wify aoma phzt kkiw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


cloud.aws.s3.bucket=nom-du-bucket
cloud.aws.credentials.access-key=YOUR_ACCESS_KEY
cloud.aws.credentials.secret-key=YOUR_SECRET_KEY
cloud.aws.region.static=us-west-2



# MinIO Configuration
minio.endpoint=http://69.62.125.51:9000
minio.access-key=invodis
minio.secret-key=Invodis@123
minio.bucket-name=invodisfiles





#logging.level.root=DEBUG
#logging.level.org.springframework=DEBUG
#logging.level.org.springframework.orm.jpa=DEBUG
#logging.level.com.itma.gestionProjet=TRACE

app.support.mail=dmamadou.tech@gmail.com
app.front.url=invodis.com

app.version=1.0.0


